# Generated by Django 5.1.5 on 2025-02-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=20)),
                ('Cat_Slug', models.SlugField(max_length=30)),
                ('Cat_Description', models.TextField(max_length=200)),
                ('Cat_Images', models.ImageField(upload_to='category/')),
                ('Date_Created', models.DateTimeField(auto_now_add=True)),
                ('Date_Modified', models.DateField(auto_now=True)),
            ],
        ),
    ]
