# Generated by Django 5.1.5 on 2025-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='Cat_Images',
            field=models.ImageField(upload_to='media/category/'),
        ),
    ]
