# Generated by Django 5.1.5 on 2025-02-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_categories_options_alter_categories_cat_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='Date_Modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
