# Generated by Django 4.2.1 on 2025-02-22 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_product', models.CharField(max_length=100)),
                ('old_product_price', models.IntegerField()),
                ('old_product_quantity', models.IntegerField()),
                ('date_purchased', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
