# Generated by Django 4.2.1 on 2025-02-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_name', models.CharField(max_length=30)),
                ('users_contact_no', models.IntegerField()),
                ('users_email', models.EmailField(max_length=254)),
                ('users_message', models.TextField(max_length=300)),
                ('contact_details_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
